apiVersion: v2
name: pedido-app
description: A Helm chart for Pedido application with backend, frontend and PostgreSQL.
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
