apiVersion: v2
name: pedido-app
description: A Helm chart for Pedido application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 15.5.18
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
