backend:
  replicaCount: 2
  image:
    repository: marianavalle22/pedidos-backend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits: { cpu: 500m, memory: 512Mi }

  readinessProbe:
    httpGet:
      path: "/questions"
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 10

  livenessProbe:
    httpGet:
      path: "/questions"
      port: http
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 10

  startupProbe:
    httpGet:
      path: "/questions"
      port: http
    failureThreshold: 30
    periodSeconds: 10

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpu:
      averageUtilization: 80

  env:
    db:
      host: "pedido-app-dev-postgresql"
      port: 5432
      name: "pedidos_db"
      user: "appuser"
      password: "apppass"

  # Creamos un secret propio para la app backend
  secrets:
    existingSecretName: ""   # deja vacío, Helm creará el secret automáticamente

frontend:
  replicaCount: 1
  image:
    repository: marianavalle22/pedidos-frontend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits: { cpu: 300m, memory: 256Mi }

postgresql:
  enabled: true
  auth:
    username: appuser
    password: apppass
    database: pedidos_db
  primary:
    persistence:
      enabled: true
      size: 1Gi

global:
  fullnameOverride: ""
  nameOverride: ""
