global:
  nameOverride: ""
  fullnameOverride: ""

backend:
  replicaCount: 1
  image:
    repository: marianavalle22/pedidos-backend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits:   { cpu: 500m, memory: 512Mi }

  readinessProbe:
    httpGet:
      path: "/questions"
      port: http
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 12
  livenessProbe:
    httpGet:
      path: "/questions"
      port: http
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 6
  startupProbe:
    httpGet:
      path: "/questions"
      port: http
    initialDelaySeconds: 10
    periodSeconds: 20

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

  env:
    db:
      # host vacío -> "<release>-postgresql"
      name: "pedidos-db"
      user: "appuser"
      password: "devpass"   

frontend:
  replicaCount: 1
  image:
    repository: marianavalle22/pedidos-frontend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits:   { cpu: 300m, memory: 256Mi }

postgresql:
  enabled: true
  auth:
    username: appuser
    password: devpass
    database: pedidos-db
  primary:
    persistence:
      enabled: true
      size: 1Gi
