global:
  nameOverride: ""
  fullnameOverride: ""

backend:
  replicaCount: 1
  image:
    repository: "marianavalle22/pedidos-backend"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    db:
      host: "" 
      port: 5432
      name: "pedidos_db"
      user: "appuser"
      password: "apppass" 
    extra: {}
  secrets:
    existingSecretName: "" 


frontend:
  replicaCount: 1
  image:
    repository: "marianavalle22/pedidos-frontend"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
  env: {}


postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "postgres"
    username: "appuser"
    password: "apppass"
    database: "pedidosdb"
  primary:
    persistence:
      enabled: true
      size: 8Gi

ingress:
  enabled: true
  host: ""
