apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: backend
data:
  {{- $host := (default (printf "%s-postgresql" .Release.Name) .Values.backend.env.db.host) }}
  {{- $port := (default 5432 .Values.backend.env.db.port) }}
  {{- $dbnm := (default (default "pedidos-db" .Values.postgresql.auth.database) .Values.backend.env.db.name) }}
  DB_HOST: {{ $host | quote }}
  DB_PORT: {{ $port | quote }}
  DB_NAME: {{ $dbnm | quote }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%v/%s" $host $port $dbnm | quote }}
