apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app: backend
type: Opaque
data:
  DB_USER: {{ .Values.backend.env.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.backend.env.db.password | b64enc }}
