{{- if not .Values.backend.secrets.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app: backend
type: Opaque
data:
  DB_USER: {{ .Values.backend.env.db.user | default "appuser" | b64enc }}
  DB_PASSWORD: {{ .Values.backend.env.db.password | default "apppass" | b64enc }}
{{- end }}
