replicaCount: 2

postgresql:
  enabled: true
  auth:
    username: produser
    password: prodpass
    database: pedidosdb
  primary:
    persistence:
      size: 2Gi

backend:
  image:
    repository: myrepo/backend
    tag: latest
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  image:
    repository: myrepo/frontend
    tag: latest
  replicaCount: 2
