backend:
  image:
    repository: laurarodleo/pedido-app-images
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080

frontend:
  image:
    repository: laurarodleo/pedido-frontend
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    type: ClusterIP
    port: 80

database:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  containerPort: 3306
  service:
    type: ClusterIP
    port: 3306
