# --- BACKEND: pedido-backend ---
backend:
  replicaCount: 2
  image:
    repository: myrepo/backend
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080
  readinessProbe:
    httpGet: { path: "/actuator/health", port: http }
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 12
  livenessProbe:
    httpGet: { path: "/actuator/health", port: http }
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 6
  startupProbe:
    httpGet: { path: "/actuator/health", port: http }
    initialDelaySeconds: 10
    periodSeconds: 20
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    db:
      host: ""        # ignorado por echo-server
      port: 5432
      name: "pedidosdb"
      user: "produser"
      password: "prodpass"
  extraEnv:
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:postgresql://pedido-app-prod-postgresql:5432/pedidosdb"
    - name: SPRING_DATASOURCE_USERNAME
      value: "produser"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "prodpass"

# --- FRONTEND: nginxdemos/hello ---
frontend:
  replicaCount: 2
  image:
    repository: myrepo/frontend
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  readinessProbe:
    httpGet: { path: "/", port: http }
    initialDelaySeconds: 3
    periodSeconds: 10
  livenessProbe:
    httpGet: { path: "/", port: http }
    initialDelaySeconds: 5
    periodSeconds: 20

# --- DB: PostgreSQL ---
postgresql:
  enabled: true
  auth:
    username: produser
    password: prodpass
    database: pedidosdb
  primary:
    persistence:
      enabled: true
      size: 2Gi

# --- INGRESS ---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: "pedido-app-prod.local"   # cambiar si tienes un DNS real
      paths:
        - path: /
          pathType: Prefix

# --- GLOBAL OVERRIDES ---
global:
  fullnameOverride: ""
  nameOverride: ""
