backend:
  replicaCount: 2
  image:
    tag: backend-prod
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 2
  image:
    tag: frontend-prod
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

db:
  auth:
    username: produser
    password: prodpass
    database: pedidosdb
  primary:
    persistence:
      size: 2Gi
