apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.env.db.host | default (printf "%s-postgresql" .Release.Name) | quote }}
  DB_PORT: {{ .Values.env.db.port | default 5432 | quote }}
  DB_NAME: {{ .Values.env.db.name | default "orders" | quote }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%v/%s" (.Values.env.db.host | default (printf "%s-postgresql" .Release.Name)) (.Values.env.db.port | default 5432) (.Values.env.db.name | default "orders") | quote }}
