replicaCount: 1

image:
  repository: laurarodleo/pedido-app-images
  tag: backend-dev
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

env:
  db:
    host: ""        
    port: 5432
    name: orders
    user: appuser
    password: apppass

resources: {}
