apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/milazroleon/pedido-app.git'
    targetRevision: main   # o la rama donde tengas el chart
    path: charts/pedido-app # carpeta donde está tu Chart.yaml
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pedido-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
